import { useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, ArrowRight, CheckCircle2, PackageCheck, ShieldAlert } from 'lucide-react'
import { useAuthStore } from '@/features/auth/authStore'
import { p32Service, type Recall, type Transfer } from '@/services/p32Service'

const messageOf = (error: unknown) => typeof error === 'object' && error && 'response' in error
  ? String((error as { response?: { data?: { detail?: string } } }).response?.data?.detail || 'Request failed')
  : error instanceof Error ? error.message : 'Request failed'
const key = () => crypto.randomUUID()

export default function P32OperationsPage() {
  const user = useAuthStore((state) => state.user)
  const client = useQueryClient()
  const [tab, setTab] = useState<'recall' | 'transfer'>('recall')
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const actionKeys = useRef<Record<string, string>>({})
  const actionKey = (name: string) => actionKeys.current[name] ??= key()
  const done = (text: string) => { setSuccess(text); setError(''); actionKeys.current = {}; client.invalidateQueries({ queryKey: ['p32'] }) }
  const failed = (error: unknown) => setError(messageOf(error))
  return <div className="space-y-5 p-6">
    <header><h1 className="text-2xl font-bold text-gray-900">Recall & Stock Transfer</h1><p className="mt-1 text-sm text-gray-500">Controlled batch isolation and inter-location movement.</p></header>
    {error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    {success && <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{success}</p>}
    <div role="tablist" className="inline-flex rounded-lg border bg-white p-1"><button role="tab" aria-selected={tab === 'recall'} onClick={() => setTab('recall')} className={`px-4 py-2 text-sm ${tab === 'recall' ? 'bg-gray-900 text-white' : ''}`}>Batch recalls</button><button role="tab" aria-selected={tab === 'transfer'} onClick={() => setTab('transfer')} className={`px-4 py-2 text-sm ${tab === 'transfer' ? 'bg-gray-900 text-white' : ''}`}>Stock transfers</button></div>
    {tab === 'recall' ? <RecallPanel user={user} actionKey={actionKey} done={done} failed={failed} /> : <TransferPanel user={user} actionKey={actionKey} done={done} failed={failed} />}
  </div>
}

type PanelProps = { user?: { id: string; role: string } | null; actionKey: (name: string) => string; done: (text: string) => void; failed: (error: unknown) => void }

function RecallPanel({ user, actionKey, done, failed }: PanelProps) {
  const [selected, setSelected] = useState<Recall>()
  const [medicineId, setMedicineId] = useState(''); const [batch, setBatch] = useState(''); const [reason, setReason] = useState(''); const [regulatory, setRegulatory] = useState('')
  const [resolution, setResolution] = useState('APPROVED_RELEASE'); const [resolutionReason, setResolutionReason] = useState('')
  const recalls = useQuery({ queryKey: ['p32', 'recalls'], queryFn: p32Service.recalls })
  const patients = useQuery({ queryKey: ['p32', 'patients', selected?.id], queryFn: () => p32Service.affectedPatients(selected!.id), enabled: Boolean(selected) })
  const create = useMutation({ mutationFn: p32Service.createRecall, onSuccess: (record) => { setSelected(record); done(`${record.reference_key} created`) }, onError: failed })
  const approve = useMutation({ mutationFn: (record: Recall) => p32Service.approveRecall(record.id, actionKey(`recall-approve-${record.id}`)), onSuccess: (record) => { setSelected(record); done(`${record.reference_key} approved`) }, onError: failed })
  const resolve = useMutation({ mutationFn: (record: Recall) => p32Service.resolveRecall(record.id, { action: resolution, reason: resolutionReason, idempotency_key: actionKey(`recall-resolve-${record.id}`) }), onSuccess: (record) => { setSelected(record); done(`${record.reference_key} resolved`) }, onError: failed })
  const manager = ['store_manager', 'hospital_admin'].includes(user?.role || '')
  const pending = create.isPending || approve.isPending || resolve.isPending
  return <div className="grid gap-5 xl:grid-cols-[minmax(320px,.8fr)_minmax(0,1.2fr)]">
    <section className="space-y-3 rounded-lg border bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><ShieldAlert className="h-5 w-5 text-rose-600" />Create batch recall</h2>
      <input aria-label="Medicine ID" placeholder="Medicine ID" value={medicineId} onChange={(event) => setMedicineId(event.target.value)} className="w-full rounded-lg border p-2" />
      <input aria-label="Batch number" placeholder="Batch number" value={batch} onChange={(event) => setBatch(event.target.value)} className="w-full rounded-lg border p-2" />
      <textarea aria-label="Recall reason" placeholder="Recall reason" value={reason} onChange={(event) => setReason(event.target.value)} className="w-full rounded-lg border p-2" />
      <input aria-label="Regulatory reference" placeholder="Regulatory reference" value={regulatory} onChange={(event) => setRegulatory(event.target.value)} className="w-full rounded-lg border p-2" />
      <button disabled={pending || !medicineId || !batch || reason.length < 10} onClick={() => create.mutate({ medicine_id: medicineId, batch_number: batch, recall_reason: reason, regulatory_reference: regulatory || undefined, idempotency_key: actionKey('recall-create') })} className="w-full rounded-lg bg-rose-700 p-2 text-white disabled:opacity-50">{create.isPending ? 'Creating...' : 'Create recall'}</button>
    </section>
    <section className="rounded-lg border bg-white"><h2 className="border-b p-4 font-semibold">Recall register</h2>{recalls.isLoading ? <p className="p-4">Loading recalls...</p> : recalls.isError ? <p role="alert" className="p-4 text-rose-700">{messageOf(recalls.error)}</p> : recalls.data?.length ? recalls.data.map((record) => <button key={record.id} onClick={() => setSelected(record)} className="flex w-full justify-between border-b p-4 text-left"><span><b>{record.reference_key}</b><small className="block">{record.batch_number} | {record.recall_reason}</small></span><b>{record.status}</b></button>) : <p className="p-4 text-gray-500">No recalls recorded.</p>}</section>
    {selected && <section className="space-y-4 border-t pt-4 xl:col-span-2"><div className="flex justify-between"><div><h2 className="font-semibold">{selected.reference_key}</h2><p>{selected.recall_reason}</p><p className="text-sm text-gray-500">Notification: {selected.notification_status}</p></div><b>{selected.status}</b></div>
      {selected.status === 'DRAFT' && manager && selected.initiated_by !== user?.id && <button disabled={pending} onClick={() => approve.mutate(selected)} className="rounded-lg bg-primary px-4 py-2 text-white">Approve recall</button>}
      {selected.status === 'DRAFT' && manager && selected.initiated_by === user?.id && <p className="text-amber-700">A different authorized manager must approve this recall.</p>}
      {selected.status === 'ACTIVE' && manager && <div className="flex flex-wrap gap-2"><select aria-label="Resolution action" value={resolution} onChange={(event) => setResolution(event.target.value)} className="rounded border p-2"><option value="SUPPLIER_RETURN">Supplier return</option><option value="APPROVED_RELEASE">Approved release</option><option value="DISPOSAL">Disposal</option></select><input aria-label="Resolution reason" value={resolutionReason} onChange={(event) => setResolutionReason(event.target.value)} className="min-w-72 rounded border p-2" /><button disabled={pending || resolutionReason.length < 10} onClick={() => resolve.mutate(selected)} className="rounded bg-primary px-4 py-2 text-white">Resolve recall</button></div>}
      <h3 className="font-semibold">Affected dispensing and patients</h3>{patients.isLoading ? <p>Loading affected patients...</p> : patients.data?.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>UHID</th><th>Patient</th><th>Phone</th><th>Quantity</th><th>Status</th></tr></thead><tbody>{patients.data.map((row) => <tr key={row.dispense_id}><td>{row.uhid}</td><td>{row.patient_name}</td><td>{row.phone}</td><td>{row.dispensed_quantity}</td><td>{row.notification_status}</td></tr>)}</tbody></table></div> : <p className="text-gray-500">No affected dispensing history.</p>}
    </section>}
  </div>
}

function TransferPanel({ user, actionKey, done, failed }: PanelProps) {
  const [source, setSource] = useState(''); const [destination, setDestination] = useState(''); const [batchId, setBatchId] = useState(''); const [quantity, setQuantity] = useState(''); const [selected, setSelected] = useState<Transfer>()
  const [received, setReceived] = useState(''); const [discrepancyType, setDiscrepancyType] = useState('SHORTAGE'); const [notes, setNotes] = useState('')
  const locations = useQuery({ queryKey: ['p32', 'locations'], queryFn: p32Service.locations }); const batches = useQuery({ queryKey: ['p32', 'batches', source], queryFn: () => p32Service.eligibleBatches(source), enabled: Boolean(source) }); const transfers = useQuery({ queryKey: ['p32', 'transfers'], queryFn: p32Service.transfers })
  const detail = useQuery({ queryKey: ['p32', 'transfer', selected?.id], queryFn: () => p32Service.transfer(selected!.id), enabled: Boolean(selected) }); const current = detail.data || selected
  const create = useMutation({ mutationFn: p32Service.createTransfer, onSuccess: (record) => { setSelected(record); done(`${record.reference_key} created`) }, onError: failed })
  const transition = useMutation({ mutationFn: ({ record, kind }: { record: Transfer; kind: 'approve' | 'dispatch' }) => kind === 'approve' ? p32Service.approveTransfer(record.id, actionKey(`approve-${record.id}`)) : p32Service.dispatchTransfer(record.id, actionKey(`dispatch-${record.id}`)), onSuccess: (record) => { setSelected(record); done(`${record.reference_key} updated`) }, onError: failed })
  const receive = useMutation({ mutationFn: (record: Transfer) => { const item = record.items?.[0]; const expected = Number(item?.transfer_quantity || 0); const actual = Number(received); return p32Service.receiveTransfer(record.id, { items: [{ transfer_item_id: item!.id, quantity_received: actual, ...(actual < expected ? { discrepancy_type: discrepancyType, discrepancy_quantity: expected - actual, discrepancy_notes: notes } : {}) }], complete_receipt: true, idempotency_key: actionKey(`receive-${record.id}`) }) }, onSuccess: (record) => { setSelected(record); done(`${record.reference_key} received`) }, onError: failed })
  const manager = ['store_manager', 'hospital_admin'].includes(user?.role || ''); const pending = create.isPending || transition.isPending || receive.isPending; const batch = batches.data?.find((item) => item.id === batchId)
  const submit = () => { const amount = Number(quantity); if (source === destination) return failed(new Error('Source and destination locations must differ')); if (!batch || amount <= 0 || amount > Number(batch.available_quantity) - Number(batch.reserved_quantity)) return failed(new Error('Quantity exceeds available stock')); create.mutate({ source_location_id: source, destination_location_id: destination, items: [{ inventory_batch_id: batch.id, quantity: amount }], idempotency_key: actionKey('transfer-create') }) }
  return <div className="space-y-5"><section className="grid gap-3 rounded-lg border bg-white p-5 md:grid-cols-2"><h2 className="flex items-center gap-2 font-semibold md:col-span-2"><ArrowRight className="h-5 w-5" />Create transfer draft</h2><select aria-label="Source location" value={source} onChange={(event) => { setSource(event.target.value); setBatchId('') }} className="rounded border p-2"><option value="">Source location</option>{locations.data?.map((item) => <option key={item.id} value={item.id}>{item.location_name}</option>)}</select><select aria-label="Destination location" value={destination} onChange={(event) => setDestination(event.target.value)} className="rounded border p-2"><option value="">Destination location</option>{locations.data?.filter((item) => item.id !== source).map((item) => <option key={item.id} value={item.id}>{item.location_name}</option>)}</select><select aria-label="Eligible batch" value={batchId} onChange={(event) => setBatchId(event.target.value)} className="rounded border p-2"><option value="">Eligible batch</option>{batches.data?.map((item) => <option key={item.id} value={item.id}>{item.batch_number} | available {Number(item.available_quantity) - Number(item.reserved_quantity)}</option>)}</select><input aria-label="Transfer quantity" type="number" value={quantity} onChange={(event) => setQuantity(event.target.value)} className="rounded border p-2" /><button disabled={pending || !source || !destination || !batchId} onClick={submit} className="rounded bg-primary p-2 text-white disabled:opacity-50 md:col-span-2">{create.isPending ? 'Creating...' : 'Create draft'}</button></section>
    <section className="rounded-lg border bg-white"><h2 className="border-b p-4 font-semibold">Transfers and in-transit stock</h2>{transfers.isLoading ? <p className="p-4">Loading transfers...</p> : transfers.data?.length ? transfers.data.map((record) => <button key={record.id} onClick={() => setSelected(record)} className="flex w-full justify-between border-b p-4 text-left"><span><b>{record.reference_key}</b><small className="block">{record.from_location_id} → {record.to_location_id} | {record.total_quantity}</small></span><b>{record.status}</b></button>) : <p className="p-4 text-gray-500">No transfers recorded.</p>}</section>
    {current && <section className="space-y-3 border-t pt-4"><div className="flex justify-between"><h2 className="font-semibold">{current.reference_key}</h2><b>{current.status}</b></div>{current.status === 'DRAFT' && manager && current.requested_by !== user?.id && <button disabled={pending} onClick={() => transition.mutate({ record: current, kind: 'approve' })} className="rounded bg-primary px-4 py-2 text-white">Approve transfer</button>}{current.status === 'DRAFT' && manager && current.requested_by === user?.id && <p className="text-amber-700">Requester cannot approve their own transfer.</p>}{current.status === 'APPROVED' && <button disabled={pending} onClick={() => transition.mutate({ record: current, kind: 'dispatch' })} className="rounded bg-primary px-4 py-2 text-white">Dispatch transfer</button>}{current.status === 'IN_TRANSIT' && current.items?.[0] && <div className="grid gap-2 md:grid-cols-2"><input aria-label="Quantity received" type="number" value={received} onChange={(event) => setReceived(event.target.value)} className="rounded border p-2" /><select aria-label="Discrepancy type" value={discrepancyType} onChange={(event) => setDiscrepancyType(event.target.value)} className="rounded border p-2"><option>SHORTAGE</option><option>DAMAGE</option><option>BATCH_MISMATCH</option></select>{Number(received) < Number(current.items[0].transfer_quantity) && <textarea aria-label="Discrepancy notes" value={notes} onChange={(event) => setNotes(event.target.value)} className="rounded border p-2 md:col-span-2" />}<button disabled={pending || Number(received) < 0 || Number(received) > Number(current.items[0].transfer_quantity) || (Number(received) < Number(current.items[0].transfer_quantity) && notes.length < 3)} onClick={() => receive.mutate(current)} className="rounded bg-primary p-2 text-white md:col-span-2">Receive stock</button></div>}{current.discrepancies?.map((row) => <p key={row.id} className="flex items-center gap-2 text-sm"><AlertTriangle className="h-4 w-4 text-amber-600" />{row.discrepancy_type}: {row.quantity} | {row.status}</p>)}{current.status === 'RECEIVED' && <p className="flex items-center gap-2 text-emerald-700"><PackageCheck className="h-4 w-4" />Destination stock received: {current.received_quantity}</p>}</section>}
    <p className="flex items-center gap-2 text-xs text-gray-500"><CheckCircle2 className="h-4 w-4" />Batch and expiry identity are preserved at receipt.</p>
  </div>
}
