import { useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, BellRing, Download, PackageSearch, RefreshCw, Settings2, WalletCards } from 'lucide-react'
import { P34_PERMISSIONS, pharmacyDashboardService, type PharmacyDashboardData } from '@/services/pharmacyDashboardService'
import { usePharmacyCapabilities } from '@/hooks/usePharmacyCapabilities'

const money = (value: string | null, currency = 'INR') => value === null ? 'Unavailable' : new Intl.NumberFormat('en-IN', { style: 'currency', currency }).format(Number(value))
const dateInput = (daysAgo = 0) => { const value = new Date(); value.setDate(value.getDate() - daysAgo); return value.toISOString().slice(0, 10) }
const messageOf = (error: unknown) => typeof error === 'object' && error && 'response' in error ? String((error as { response?: { data?: { detail?: string } } }).response?.data?.detail || 'Request failed') : error instanceof Error ? error.message : 'Request failed'

type View = 'dashboard' | 'reports' | 'alerts' | 'configuration'

export default function PharmacyDashboardPage() {
  const client = useQueryClient()
  const { hasPermission } = usePharmacyCapabilities()
  const [view, setView] = useState<View>('dashboard')
  const [locationId, setLocationId] = useState('')
  const dashboard = useQuery({ queryKey: ['pharmacy-dashboard', locationId], queryFn: () => pharmacyDashboardService.dashboard(locationId || undefined), refetchInterval: 60_000 })
  const tabs: { id: View; label: string; permission: string }[] = [
    { id: 'dashboard', label: 'Overview', permission: P34_PERMISSIONS.dashboard },
    { id: 'reports', label: 'Reports', permission: P34_PERMISSIONS.reports },
    { id: 'alerts', label: 'Alerts', permission: P34_PERMISSIONS.alerts },
    { id: 'configuration', label: 'Configuration', permission: P34_PERMISSIONS.configure },
  ]
  const openReport = (report: string) => { setView('reports'); window.history.replaceState(null, '', `/pharmacy/dashboard?report=${encodeURIComponent(report)}`) }

  return <div className="min-h-full bg-[#f5f7f4] p-4 sm:p-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-emerald-900/15 pb-5">
      <div><p className="text-xs font-semibold uppercase text-emerald-800">Pharmacy operations</p><h1 className="mt-1 text-2xl font-bold text-gray-950">Pharmacy Dashboard</h1><p className="mt-1 text-sm text-gray-600">Facility-scoped sales, dispensing, purchasing, inventory, alerts, and reports.</p></div>
      <div className="flex flex-wrap items-end gap-2"><label className="text-xs font-medium text-gray-600">Location filter<input aria-label="Pharmacy location filter" value={locationId} onChange={event => setLocationId(event.target.value.trim())} placeholder="All authorized locations" className="mt-1 block w-56 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm" /></label><button type="button" title="Refresh dashboard" aria-label="Refresh dashboard" onClick={() => client.invalidateQueries({ queryKey: ['pharmacy-dashboard'] })} className="grid h-10 w-10 place-items-center rounded-md border border-gray-300 bg-white text-gray-700"><RefreshCw className="h-4 w-4" /></button></div>
    </header>
    <nav aria-label="Pharmacy dashboard views" className="my-5 flex gap-1 overflow-x-auto border-b border-gray-300">{tabs.filter(tab => hasPermission(tab.permission)).map(tab => <button key={tab.id} onClick={() => setView(tab.id)} className={`border-b-2 px-4 py-2 text-sm font-medium ${view === tab.id ? 'border-emerald-700 text-emerald-800' : 'border-transparent text-gray-600'}`}>{tab.label}</button>)}</nav>
    {view === 'dashboard' && (dashboard.isLoading ? <DashboardSkeleton /> : dashboard.isError ? <StateMessage error={messageOf(dashboard.error)} /> : dashboard.data ? <Overview data={dashboard.data} openReport={openReport} /> : null)}
    {view === 'reports' && <Reports locationId={locationId} canExport={hasPermission(P34_PERMISSIONS.export)} />}
    {view === 'alerts' && <Alerts locationId={locationId} canAcknowledge={hasPermission(P34_PERMISSIONS.acknowledge)} />}
    {view === 'configuration' && hasPermission(P34_PERMISSIONS.configure) && <Configuration locationId={locationId} />}
  </div>
}

function Overview({ data, openReport }: { data: PharmacyDashboardData; openReport: (report: string) => void }) {
  const { cards } = data
  const cardsList = [
    ['Prescriptions pending', cards.prescriptions_pending, 'dispensing'], ['Dispensed today', `${cards.dispensed_today.count} / ${cards.dispensed_today.quantity}`, 'dispensing'],
    ['Purchases / GRNs today', cards.purchases_today.count, 'purchase-grn'], ['Patient returns today', cards.patient_returns_today.count, 'patient-returns'],
    ['Supplier returns today', cards.supplier_returns_today.count, 'supplier-returns'], ['Stock adjustments today', cards.stock_adjustments_today.count, 'stock-adjustments'],
    ['Low-stock items', cards.low_stock_items, 'reorder'], ['Out-of-stock items', cards.out_of_stock_items, 'reorder'],
    ['Outside purchases', cards.outside_purchases.item_count, 'outside-purchases'],
  ] as const
  return <div className="space-y-5">
    <div className="flex flex-wrap justify-between gap-3 text-xs text-gray-600"><span>Business date {data.metadata.business_date} in {data.metadata.timezone}</span><span>Facility {data.metadata.facility_id}</span></div>
    {data.financial_data_visible && <section className="border-l-4 border-emerald-700 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-emerald-700" /><h2 className="font-semibold">Today's Pharmacy sales</h2></div><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(cards.sales).filter(([key]) => key !== 'currency').map(([key, value]) => <div key={key}><p className="text-xs uppercase text-gray-500">{key.replaceAll('_', ' ')}</p><p className="mt-1 text-lg font-bold text-gray-950">{money(String(value), cards.sales.currency)}</p></div>)}</div></section>}
    {!data.financial_data_visible && <p className="border-l-4 border-amber-500 bg-amber-50 p-3 text-sm text-amber-900">Operational view. Financial totals and valuation require additional reporting access.</p>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cardsList.map(([label, value, report]) => <button key={label} onClick={() => openReport(report)} className="flex min-h-24 items-center justify-between border border-gray-200 bg-white p-4 text-left shadow-sm hover:border-emerald-600"><span><span className="block text-sm font-medium text-gray-600">{label}</span><span className="mt-2 block text-2xl font-bold text-gray-950">{value}</span></span><PackageSearch className="h-5 w-5 text-emerald-700" /></button>)}</section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="border border-gray-200 bg-white p-5"><h2 className="font-semibold">Expiring stock</h2><div className="mt-4 grid grid-cols-3 gap-3">{[['0-30 days', cards.expiring_stock['0_30']], ['31-60 days', cards.expiring_stock['31_60']], ['61-90 days', cards.expiring_stock['61_90']]].map(([label, value]) => <button key={label} onClick={() => openReport('expiry')} className="border-l-2 border-amber-500 bg-amber-50 p-3 text-left"><b className="block text-xl">{value}</b><span className="text-xs text-gray-600">{label}</span></button>)}</div></div>{data.financial_data_visible && <div className="border border-gray-200 bg-white p-5"><h2 className="font-semibold">Inventory valuation</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><Value label="Available" value={money(cards.inventory_valuation.available)} /><Value label="Reserved" value={money(cards.inventory_valuation.reserved)} /><Value label="Quarantined" value={money(cards.inventory_valuation.quarantined)} /><Value label="Total physical" value={money(cards.inventory_valuation.total_physical)} /></dl>{Number(cards.inventory_valuation.unvalued_quantity) > 0 && <p className="mt-3 text-sm text-rose-700">Unvalued quantity: {cards.inventory_valuation.unvalued_quantity}</p>}</div>}</section>
  </div>
}

function Value({ label, value }: { label: string; value: string }) { return <div><dt className="text-gray-500">{label}</dt><dd className="font-semibold text-gray-950">{value}</dd></div> }
function DashboardSkeleton() { return <div role="status" className="grid gap-3 sm:grid-cols-3">{Array.from({ length: 9 }, (_, index) => <div key={index} className="h-24 animate-pulse bg-gray-200" />)}</div> }
function StateMessage({ error }: { error: string }) { return <div role="alert" className="border-l-4 border-rose-600 bg-rose-50 p-4 text-rose-800">{error}</div> }

function Reports({ locationId, canExport }: { locationId: string; canExport: boolean }) {
  const initialReport = new URLSearchParams(window.location.search).get('report') || 'current-stock'
  const [reportName, setReportName] = useState(initialReport)
  const [startDate, setStartDate] = useState(dateInput(30)); const [endDate, setEndDate] = useState(dateInput()); const [page, setPage] = useState(1)
  const [medicineId, setMedicineId] = useState(''); const [batchNumber, setBatchNumber] = useState(''); const [supplierId, setSupplierId] = useState('')
  const [reportStatus, setReportStatus] = useState(''); const [alertType, setAlertType] = useState('')
  const filters = { start_date: startDate, end_date: endDate, pharmacy_location_id: locationId || undefined, medicine_id: medicineId || undefined, batch_number: batchNumber || undefined, supplier_id: supplierId || undefined, status: reportStatus || undefined, alert_type: alertType || undefined }
  const catalogue = useQuery({ queryKey: ['pharmacy-report-catalogue'], queryFn: pharmacyDashboardService.reportCatalogue })
  const report = useQuery({ queryKey: ['pharmacy-report', reportName, filters, page], queryFn: () => pharmacyDashboardService.report(reportName, { ...filters, page, page_size: 50 }) })
  const download = useMutation({ mutationFn: () => pharmacyDashboardService.exportReport(reportName, filters), onSuccess: blob => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `pharmacy-${reportName}.csv`; link.click(); URL.revokeObjectURL(url) } })
  const columns = report.data?.items[0] ? Object.keys(report.data.items[0]) : []
  return <section className="space-y-4"><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Report<select aria-label="Pharmacy report" value={reportName} onChange={event => { setReportName(event.target.value); setPage(1) }} className="mt-1 block rounded-md border bg-white px-3 py-2">{catalogue.data?.map(name => <option key={name}>{name}</option>)}</select></label><label className="text-sm">From<input aria-label="Report start date" type="date" value={startDate} onChange={event => setStartDate(event.target.value)} className="mt-1 block rounded-md border px-3 py-2" /></label><label className="text-sm">To<input aria-label="Report end date" type="date" value={endDate} onChange={event => setEndDate(event.target.value)} className="mt-1 block rounded-md border px-3 py-2" /></label><label className="text-sm">Medicine ID<input aria-label="Report medicine ID" value={medicineId} onChange={event => { setMedicineId(event.target.value.trim()); setPage(1) }} className="mt-1 block w-44 rounded-md border px-3 py-2" /></label><label className="text-sm">Batch<input aria-label="Report batch number" value={batchNumber} onChange={event => { setBatchNumber(event.target.value); setPage(1) }} className="mt-1 block w-36 rounded-md border px-3 py-2" /></label><label className="text-sm">Supplier ID<input aria-label="Report supplier ID" value={supplierId} onChange={event => { setSupplierId(event.target.value.trim()); setPage(1) }} className="mt-1 block w-44 rounded-md border px-3 py-2" /></label><label className="text-sm">Status<input aria-label="Report status" value={reportStatus} onChange={event => { setReportStatus(event.target.value.trim()); setPage(1) }} className="mt-1 block w-36 rounded-md border px-3 py-2" /></label><label className="text-sm">Alert type<select aria-label="Report alert type" value={alertType} onChange={event => { setAlertType(event.target.value); setPage(1) }} className="mt-1 block rounded-md border bg-white px-3 py-2"><option value="">All</option>{['LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRY', 'UNUSUAL_ADJUSTMENT', 'REPEATED_VARIANCE', 'UNUSUAL_RETURN'].map(value => <option key={value}>{value}</option>)}</select></label>{canExport && <button onClick={() => download.mutate()} disabled={download.isPending} className="flex items-center gap-2 rounded-md bg-emerald-800 px-4 py-2 text-sm font-semibold text-white"><Download className="h-4 w-4" />{download.isPending ? 'Exporting...' : 'Export CSV'}</button>}</div>
    {report.isLoading ? <p role="status">Loading report...</p> : report.isError ? <StateMessage error={messageOf(report.error)} /> : report.data?.items.length ? <div className="overflow-x-auto border bg-white"><table className="min-w-full text-sm"><thead className="bg-gray-100"><tr>{columns.map(column => <th key={column} className="whitespace-nowrap px-3 py-2 text-left">{column.replaceAll('_', ' ')}</th>)}</tr></thead><tbody>{report.data.items.map((item, index) => <tr key={String(item.id || index)} className="border-t">{columns.map(column => <td key={column} className="max-w-72 truncate px-3 py-2">{typeof item[column] === 'object' ? JSON.stringify(item[column]) : String(item[column] ?? '')}</td>)}</tr>)}</tbody></table></div> : <p className="border bg-white p-8 text-center text-gray-500">No report rows match these filters.</p>}
    {report.data && <div className="flex justify-between text-sm"><button disabled={page === 1} onClick={() => setPage(value => value - 1)}>Previous</button><span>Page {page} · {report.data.total} rows</span><button disabled={page * report.data.page_size >= report.data.total} onClick={() => setPage(value => value + 1)}>Next</button></div>}
  </section>
}

function Alerts({ locationId, canAcknowledge }: { locationId: string; canAcknowledge: boolean }) {
  const client = useQueryClient(); const keys = useRef<Record<string, string>>({}); const [status, setStatus] = useState('OPEN'); const [notes, setNotes] = useState<Record<string, string>>({})
  const alerts = useQuery({ queryKey: ['pharmacy-alerts', locationId, status], queryFn: () => pharmacyDashboardService.alerts({ pharmacy_location_id: locationId || undefined, status: status || undefined }) })
  const acknowledge = useMutation({ mutationFn: (id: string) => pharmacyDashboardService.acknowledge(id, notes[id] || '', keys.current[id] ??= crypto.randomUUID()), onSuccess: () => { keys.current = {}; client.invalidateQueries({ queryKey: ['pharmacy-alerts'] }); client.invalidateQueries({ queryKey: ['pharmacy-dashboard'] }) } })
  return <section><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><BellRing className="h-5 w-5 text-amber-700" />Operational alerts</h2><select aria-label="Alert status" value={status} onChange={event => setStatus(event.target.value)} className="rounded border bg-white px-3 py-2 text-sm"><option>OPEN</option><option>ACKNOWLEDGED</option><option>RESOLVED</option><option value="">All</option></select></div>{alerts.isLoading ? <p role="status">Loading alerts...</p> : alerts.isError ? <StateMessage error={messageOf(alerts.error)} /> : alerts.data?.items.length ? <div className="divide-y border bg-white">{alerts.data.items.map(alert => <article key={alert.id} className="p-4"><div className="flex gap-3"><AlertTriangle className={`h-5 w-5 ${alert.severity === 'CRITICAL' ? 'text-rose-700' : 'text-amber-600'}`} /><div className="flex-1"><div className="flex justify-between"><h3 className="font-semibold">{alert.title}</h3><span className="text-xs font-semibold">{alert.status}</span></div><p className="mt-1 text-sm text-gray-600">{alert.message}</p>{canAcknowledge && alert.status === 'OPEN' && <div className="mt-3 flex gap-2"><input aria-label={`Acknowledgement note for ${alert.title}`} value={notes[alert.id] || ''} onChange={event => { keys.current[alert.id] = ''; setNotes(value => ({ ...value, [alert.id]: event.target.value })) }} placeholder="Mandatory acknowledgement note" className="flex-1 rounded border px-3 py-2 text-sm" /><button disabled={(notes[alert.id] || '').trim().length < 3 || acknowledge.isPending} onClick={() => acknowledge.mutate(alert.id)} className="rounded bg-amber-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Acknowledge</button></div>}</div></div></article>)}</div> : <p className="border bg-white p-8 text-center text-gray-500">No alerts match this status.</p>}</section>
}

function Configuration({ locationId }: { locationId: string }) {
  const client = useQueryClient(); const key = useRef(''); const configuration = useQuery({ queryKey: ['pharmacy-alert-configuration', locationId], queryFn: () => pharmacyDashboardService.configuration(locationId || undefined) })
  const [reorder, setReorder] = useState(''); const [expiry, setExpiry] = useState(''); const [error, setError] = useState('')
  const update = useMutation({ mutationFn: () => pharmacyDashboardService.updateConfiguration({ pharmacy_location_id: locationId || undefined, reorder_level: Number(reorder || configuration.data.reorder_level), expiry_horizon_days: Number(expiry || configuration.data.expiry_horizon_days), high_value_thresholds: configuration.data.high_value_thresholds, quantity_percentage_threshold: configuration.data.quantity_percentage_threshold, repeated_event_count: configuration.data.repeated_event_count, lookback_days: configuration.data.lookback_days, version: configuration.data.version }, key.current ||= crypto.randomUUID()), onSuccess: () => { key.current = ''; setError(''); client.invalidateQueries({ queryKey: ['pharmacy-alert-configuration'] }); client.invalidateQueries({ queryKey: ['pharmacy-dashboard'] }) }, onError: value => setError(messageOf(value)) })
  if (configuration.isLoading) return <p role="status">Loading configuration...</p>; if (configuration.isError) return <StateMessage error={messageOf(configuration.error)} />
  return <section className="max-w-2xl border bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Settings2 className="h-5 w-5 text-emerald-700" />Effective alert configuration</h2><p className="mt-1 text-xs text-gray-500">Effective from {configuration.data.effective_from}; version {configuration.data.version}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Reorder level<input aria-label="Reorder level" type="number" min="0" value={reorder || configuration.data.reorder_level} onChange={event => { key.current = ''; setReorder(event.target.value) }} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Expiry horizon days<input aria-label="Expiry horizon days" type="number" min="1" max="366" value={expiry || configuration.data.expiry_horizon_days} onChange={event => { key.current = ''; setExpiry(event.target.value) }} className="mt-1 w-full rounded border px-3 py-2" /></label></div>{error && <p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}<button onClick={() => update.mutate()} disabled={update.isPending} className="mt-5 rounded bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">{update.isPending ? 'Saving...' : 'Save configuration'}</button></section>
}
