import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import SupplierReturnsPage from './SupplierReturnsPage'
import { supplierReturnService } from '@/services/returnsService'
import { masterDataService } from '@/services/masterDataService'

vi.mock('@/services/returnsService', () => ({ supplierReturnService: { eligibility: vi.fn(), list: vi.fn(), create: vi.fn(), approve: vi.fn(), dispatch: vi.fn() } }))
vi.mock('@/services/masterDataService', () => ({ masterDataService: { listSuppliers: vi.fn() } }))
const returns = vi.mocked(supplierReturnService)
const masters = vi.mocked(masterDataService)
const renderPage = () => render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><SupplierReturnsPage /></QueryClientProvider>)
const batch = (id: string, number: string, available: string, cost = '12.50') => ({ inventory_batch_id: id, batch_number: number, medicine_name: 'P30 Supplier Medicine', expiry_date: '2027-12-31T00:00:00Z', available_quantity: available, original_received_quantity: '10', eligible_return_quantity: available, unit_cost: cost, supplier_id: 'supplier-1', goods_receipt_id: 'grn-1', purchase_order_id: 'po-1' })
const eligibility = (items = [batch('batch-1', 'P30-SUP-A', '5')]) => ({ supplier_id: 'supplier-1', supplier_name: 'P30 Supplier', goods_receipt_id: 'grn-1', purchase_order_id: 'po-1', facility_id: 'facility-1', pharmacy_location_id: 'location-1', items })
const record = (status: 'REQUESTED' | 'APPROVED' | 'DISPATCHED' = 'REQUESTED') => ({ id: 'supplier-return-1', tenant_id: 'tenant-1', facility_id: 'facility-1', pharmacy_location_id: 'location-1', supplier_id: 'supplier-1', goods_receipt_id: 'grn-1', status, reference_key: 'SR-P30-001', return_reason: 'Damaged received stock', total_return_quantity: '1', total_return_value: '12.50', requested_at: '2026-08-30T00:00:00Z', created_at: '2026-08-30T00:00:00Z', updated_at: '2026-08-30T00:00:00Z', items: [] })

beforeEach(() => { vi.clearAllMocks(); masters.listSuppliers.mockResolvedValue([{ id: 'supplier-1', supplier_code: 'P30', supplier_name: 'P30 Supplier', is_active: true }, { id: 'inactive', supplier_code: 'OLD', supplier_name: 'Inactive', is_active: false }]); returns.eligibility.mockResolvedValue(eligibility()); returns.list.mockResolvedValue({ items: [], page: 1, page_size: 20, total: 0, total_pages: 0 }); returns.create.mockResolvedValue(record()); returns.approve.mockResolvedValue(record('APPROVED')); returns.dispatch.mockResolvedValue(record('DISPATCHED')) })
afterEach(cleanup)
async function selectSupplier() { renderPage(); await screen.findByRole('option', { name: 'P30 Supplier' }); await userEvent.setup().selectOptions(screen.getByLabelText('Active supplier'), 'supplier-1'); await screen.findByLabelText('Return quantity for P30-SUP-A') }

describe('SupplierReturnsPage P30', () => {
  it('renders supplier loading, error, and empty eligibility states', async () => { masters.listSuppliers.mockImplementation(() => new Promise(() => {})); renderPage(); expect(screen.getByText('Create return')).toBeInTheDocument(); cleanup(); masters.listSuppliers.mockRejectedValue(new Error('Supplier lookup failed')); renderPage(); await screen.findByText('Supplier lookup failed'); cleanup(); masters.listSuppliers.mockResolvedValue([{ id: 'supplier-1', supplier_code: 'P30', supplier_name: 'P30 Supplier', is_active: true }]); returns.eligibility.mockResolvedValue(eligibility([])); renderPage(); await screen.findByRole('option', { name: 'P30 Supplier' }); fireEvent.change(screen.getByLabelText('Active supplier'), { target: { value: 'supplier-1' } }); expect(await screen.findByText('No eligible inventory batches for this supplier.')).toBeInTheDocument() })
  it('filters active suppliers and renders GRN, location, medicine, batch, and available quantity', async () => { await selectSupplier(); expect(screen.queryByRole('option', { name: 'Inactive' })).toBeNull(); expect(screen.getByText(/GRN grn-1/)).toBeInTheDocument(); expect(screen.getByText(/Available 5; eligible 5/)).toBeInTheDocument(); expect(returns.eligibility).toHaveBeenCalledWith({ supplier_id: 'supplier-1' }) })
  it('submits multiple eligible batches with backend unit costs and blocks excessive or non-positive quantities', async () => { returns.eligibility.mockResolvedValue(eligibility([batch('batch-1', 'P30-SUP-A', '5', '12.50'), batch('batch-2', 'P30-SUP-B', '2', '8.25')])); await selectSupplier(); fireEvent.change(screen.getByLabelText('Return quantity for P30-SUP-A'), { target: { value: '6' } }); fireEvent.change(screen.getByLabelText('Return reason'), { target: { value: 'Damaged received stock' } }); fireEvent.click(screen.getByRole('button', { name: 'Submit return' })); expect(await screen.findByRole('alert')).toHaveTextContent('exceeds'); fireEvent.change(screen.getByLabelText('Return quantity for P30-SUP-A'), { target: { value: '2' } }); fireEvent.change(screen.getByLabelText('Return quantity for P30-SUP-B'), { target: { value: '1' } }); await waitFor(() => expect(screen.getByLabelText('Return quantity for P30-SUP-B')).toHaveValue(1)); fireEvent.click(screen.getByRole('button', { name: 'Submit return' })); await waitFor(() => expect(returns.create).toHaveBeenCalledOnce()); expect(returns.create).toHaveBeenCalledWith(expect.objectContaining({ supplier_id: 'supplier-1', goods_receipt_id: 'grn-1', items: [{ inventory_batch_id: 'batch-1', returned_quantity: 2, unit_cost: 12.5 }, { inventory_batch_id: 'batch-2', returned_quantity: 1, unit_cost: 8.25 }] })) })
  it('shows only valid lifecycle actions and invokes approve then dispatch', async () => { returns.list.mockResolvedValueOnce({ items: [record('REQUESTED')], page: 1, page_size: 20, total: 1, total_pages: 1 }); renderPage(); await screen.findByText('SR-P30-001'); expect(screen.getByRole('button', { name: 'Approve' })).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Dispatch' })).toBeNull(); await userEvent.setup().click(screen.getByRole('button', { name: 'Approve' })); await waitFor(() => expect(returns.approve).toHaveBeenCalledOnce()); cleanup(); returns.list.mockResolvedValueOnce({ items: [record('APPROVED')], page: 1, page_size: 20, total: 1, total_pages: 1 }); renderPage(); await screen.findByText('SR-P30-001'); expect(screen.queryByRole('button', { name: 'Approve' })).toBeNull(); await userEvent.setup().click(screen.getByRole('button', { name: 'Dispatch' })); await waitFor(() => expect(returns.dispatch).toHaveBeenCalledOnce()) })
})
