import { expect, test, type Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createPageDiagnostics, type PageDiagnosticsCollector } from './support/pageDiagnostics'

const pharmacist = { username: 'e2e_pharmacist_task7', password: 'E2ePharmacist@123' }
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
function resetP30() { execFileSync(process.env.PYTHON ?? 'python', [path.join(repoRoot, 'backend', 'tests', 'e2e_seed_task7.py'), 'seed_p30_scenario'], { cwd: path.join(repoRoot, 'backend'), stdio: 'inherit', env: { ...process.env, E2E_ENVIRONMENT: 'E2E', E2E_ALLOW_DESTRUCTIVE_RESET: 'true', DATABASE_URL: process.env.E2E_DATABASE_URL ?? 'postgresql+asyncpg://hospital_user:hospital_pass@localhost:5433/hospital', SECRET_KEY: process.env.SECRET_KEY ?? 'test-secret-key' } }) }
function snapshotP30() { return JSON.parse(execFileSync(process.env.PYTHON ?? 'python', [path.join(repoRoot, 'backend', 'tests', 'e2e_seed_task7.py'), 'snapshot_p30'], { cwd: path.join(repoRoot, 'backend'), encoding: 'utf8', env: { ...process.env, DATABASE_URL: process.env.E2E_DATABASE_URL ?? 'postgresql+asyncpg://hospital_user:hospital_pass@localhost:5433/hospital', SECRET_KEY: process.env.SECRET_KEY ?? 'test-secret-key' } })) }
async function login(page: Page) { await page.goto('/login'); await page.getByPlaceholder(/you@hospital/i).fill(pharmacist.username); await page.locator('input[type=password]').fill(pharmacist.password); await page.getByRole('button', { name: /sign in/i }).click(); await expect(page).toHaveURL(/pharmacy/) }

test.describe.serial('P30 supplier returns', () => {
  let diagnostics: PageDiagnosticsCollector
  test.beforeEach(() => resetP30())
  test.beforeEach(async ({ page }) => { diagnostics = createPageDiagnostics(page) })
  test.afterEach(async ({ page: _page }, info) => diagnostics.flush(info))
  test('creates, approves, and dispatches a supplier return through Chromium', async ({ page }) => {
    await login(page); await page.goto('/pharmacy/supplier-returns'); await expect(page.getByRole('heading', { name: 'Supplier Returns' })).toBeVisible(); await page.getByLabel('Active supplier').selectOption({ label: 'E2E Supplier' }); await expect(page.getByText(/P30-SUP-A/)).toBeVisible(); await page.getByLabel('Return quantity for P30-SUP-A').fill('2'); await page.getByLabel('Return reason').fill('Damaged received stock'); const created = page.waitForResponse((response) => response.url().includes('/returns/supplier-returns') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Submit return' }).click(); const createdResponse = await created; expect(createdResponse.ok()).toBeTruthy(); const returnId = (await createdResponse.json()).id; await expect(page.getByText('SR-', { exact: false })).toBeVisible(); const approve = page.waitForResponse((response) => response.url().includes('/approve') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Approve' }).click(); expect((await approve).ok()).toBeTruthy(); const dispatch = page.waitForResponse((response) => response.url().includes('/dispatch') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Dispatch' }).click(); const dispatchResponse = await dispatch; expect(dispatchResponse.ok()).toBeTruthy(); await expect(page.getByText('DISPATCHED', { exact: true })).toBeVisible(); const snapshot = snapshotP30(); expect(snapshot.supplier_returns).toHaveLength(1); expect(snapshot.supplier_returns[0].status).toBe('DISPATCHED'); expect(snapshot.batches.find((batch: { batch_number: string }) => batch.batch_number === 'P30-SUP-A').available_quantity).toBe('8.000'); expect(snapshot.ledger).toEqual([{ transaction_type: 'SUPPLIER_RETURN', batch_number: 'P30-SUP-A', quantity: '-2.000' }]); const replay = await page.request.post(`/api/v1/returns/supplier-returns/${returnId}/dispatch`, { headers: { Authorization: dispatchResponse.request().headers().authorization ?? '' } }); expect(replay.status()).toBe(400); const afterReplay = snapshotP30(); expect(afterReplay.batches.find((batch: { batch_number: string }) => batch.batch_number === 'P30-SUP-A').available_quantity).toBe('8.000'); expect(afterReplay.ledger).toEqual(snapshot.ledger)
  })
})
