import { expect, test, type Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createPageDiagnostics, type PageDiagnosticsCollector } from './support/pageDiagnostics'

const pharmacist = { username: 'e2e_pharmacist_task7', password: 'E2ePharmacist@123' }
const nurse = { username: 'e2e_receptionist_task7', password: 'E2eReception@123' }
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
function resetP30() { execFileSync(process.env.PYTHON ?? 'python', [path.join(repoRoot, 'backend', 'tests', 'e2e_seed_task7.py'), 'seed_p30_scenario'], { cwd: path.join(repoRoot, 'backend'), stdio: 'inherit', env: { ...process.env, E2E_ENVIRONMENT: 'E2E', E2E_ALLOW_DESTRUCTIVE_RESET: 'true', DATABASE_URL: process.env.E2E_DATABASE_URL ?? 'postgresql+asyncpg://hospital_user:hospital_pass@localhost:5433/hospital', SECRET_KEY: process.env.SECRET_KEY ?? 'test-secret-key' } }) }
function snapshotP30() { return JSON.parse(execFileSync(process.env.PYTHON ?? 'python', [path.join(repoRoot, 'backend', 'tests', 'e2e_seed_task7.py'), 'snapshot_p30'], { cwd: path.join(repoRoot, 'backend'), encoding: 'utf8', env: { ...process.env, DATABASE_URL: process.env.E2E_DATABASE_URL ?? 'postgresql+asyncpg://hospital_user:hospital_pass@localhost:5433/hospital', SECRET_KEY: process.env.SECRET_KEY ?? 'test-secret-key' } })) }
async function login(page: Page, user = pharmacist) { await page.goto('/login'); await page.getByPlaceholder(/you@hospital/i).fill(user.username); await page.locator('input[type=password]').fill(user.password); await page.getByRole('button', { name: /sign in/i }).click(); await expect(page).toHaveURL(/pharmacy/) }

test.describe.serial('P30 patient returns', () => {
  let diagnostics: PageDiagnosticsCollector
  test.beforeEach(() => resetP30())
  test.beforeEach(async ({ page }) => { diagnostics = createPageDiagnostics(page) })
  test.afterEach(async ({}, info) => diagnostics.flush(info))
  test('creates a single-batch patient return through Chromium', async ({ page }) => {
    await login(page); await page.goto('/pharmacy/patient-returns'); await expect(page.getByRole('heading', { name: 'Patient Returns' })).toBeVisible()
    await page.getByPlaceholder('Patient name or UHID').fill('E2E-P30-SINGLE'); await page.getByLabel('Eligible dispensing record').selectOption({ index: 1 })
    await expect(page.getByText('P30 Single Medicine')).toBeVisible(); await expect(page.getByText(/P30-SINGLE-BATCH/)).toBeVisible()
    await page.getByLabel('Return quantity for P30-SINGLE-BATCH').fill('2'); await page.getByLabel('Return reason').fill('Sealed patient return'); const create = page.waitForResponse((response) => response.url().includes('/returns/patient-returns') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Submit return' }).click(); expect((await create).ok()).toBeTruthy(); await expect(page.getByText('REQUESTED', { exact: true })).toBeVisible(); expect(snapshotP30().ledger).toEqual([]); const validate = page.waitForResponse((response) => response.url().includes('/validate') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Validate' }).click(); expect((await validate).ok()).toBeTruthy(); await expect(page.getByText('VALIDATED', { exact: true })).toBeVisible(); expect(snapshotP30().ledger).toEqual([]); const accept = page.waitForResponse((response) => response.url().includes('/accept') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Accept' }).click(); expect((await accept).ok()).toBeTruthy(); const snapshot = snapshotP30(); expect(snapshot.patient_returns).toHaveLength(1); expect(snapshot.patient_returns[0].status).toBe('REFUND_PENDING'); expect(snapshot.patient_allocations).toEqual([{ batch_number: 'P30-SINGLE-BATCH', returned_quantity: '2.000' }]); expect(snapshot.batches.find((batch: { batch_number: string }) => batch.batch_number === 'P30-SINGLE-BATCH').available_quantity).toBe('2.000'); expect(snapshot.ledger).toEqual([{ transaction_type: 'PATIENT_RETURN_RESTOCK', batch_number: 'P30-SINGLE-BATCH', quantity: '2.000' }])
  })
  test('creates a multi-batch patient return through Chromium', async ({ page }) => {
    await login(page); await page.goto('/pharmacy/patient-returns'); await page.getByPlaceholder('Patient name or UHID').fill('E2E-P30-MULTI'); await page.getByLabel('Eligible dispensing record').selectOption({ index: 1 }); await expect(page.getByText('P30 Multi Medicine')).toBeVisible(); await page.getByLabel('Return quantity for P30-MULTI-A').fill('1'); await page.getByLabel('Return quantity for P30-MULTI-B').fill('2'); await page.getByLabel('Return reason').fill('Sealed patient return'); const create = page.waitForResponse((response) => response.url().includes('/returns/patient-returns') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Submit return' }).click(); expect((await create).ok()).toBeTruthy(); await page.getByRole('button', { name: 'Validate' }).click(); await expect(page.getByRole('button', { name: 'Accept' })).toBeVisible(); const accept = page.waitForResponse((response) => response.url().includes('/accept') && response.request().method() === 'POST'); await page.getByRole('button', { name: 'Accept' }).click(); expect((await accept).ok()).toBeTruthy(); const snapshot = snapshotP30(); expect(snapshot.patient_allocations).toEqual([{ batch_number: 'P30-MULTI-A', returned_quantity: '1.000' }, { batch_number: 'P30-MULTI-B', returned_quantity: '2.000' }]); expect(snapshot.ledger).toEqual([{ transaction_type: 'PATIENT_RETURN_RESTOCK', batch_number: 'P30-MULTI-A', quantity: '1.000' }, { transaction_type: 'PATIENT_RETURN_RESTOCK', batch_number: 'P30-MULTI-B', quantity: '2.000' }])
  })
  test('blocks an unauthorized user from the patient return route', async ({ page }) => { await page.goto('/login'); await page.getByPlaceholder(/you@hospital/i).fill(nurse.username); await page.locator('input[type=password]').fill(nurse.password); await page.getByRole('button', { name: /sign in/i }).click(); await expect(page).toHaveURL(/patients/); await page.goto('/pharmacy/patient-returns'); await expect(page).not.toHaveURL(/patient-returns/) })
  test('visibly rejects an excessive patient return without stock movement', async ({ page }) => { await login(page); await page.goto('/pharmacy/patient-returns'); await page.getByPlaceholder('Patient name or UHID').fill('E2E-P30-SINGLE'); await page.getByLabel('Eligible dispensing record').selectOption({ index: 1 }); await page.getByLabel('Return quantity for P30-SINGLE-BATCH').fill('6'); await page.getByLabel('Return reason').fill('Sealed patient return'); await page.getByRole('button', { name: 'Submit return' }).click(); await expect(page.getByRole('alert')).toContainText('exceeds'); expect(snapshotP30().ledger).toEqual([]) })
})
